"""
app/doc_generator.py
---------------------
Renders the final polished .docx from the plan + drafted (and possibly
reflection-revised) sections.

python-docx is pure Python (no shelling out to LibreOffice/Pandoc at request
time), gives full control over styles, and its low-level docx.oxml escape
hatch is what makes the Table-of-Contents and page-number *fields* possible
-- neither is exposed by the high-level API.

Note on the TOC field: it's a real Word `TOC` field, the same mechanism Word
itself uses. It shows placeholder text until opened in Microsoft Word, which
prompts to update fields on open -- this is standard Word behavior, not a bug.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.shared import Pt, RGBColor
from docx.table import _Cell
from docx.text.paragraph import Paragraph
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from app import config
from app.schemas import Plan, SectionContent

ACCENT_COLOR_HEX = "1F4E79"  # dark corporate blue
ACCENT_COLOR = RGBColor.from_string(ACCENT_COLOR_HEX)


def _add_toc_field(doc: Document) -> None:
    paragraph = doc.add_paragraph()
    run = paragraph.add_run()
    fld_begin = OxmlElement("w:fldChar")
    fld_begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = 'TOC \\o "1-2" \\h \\z \\u'
    fld_sep = OxmlElement("w:fldChar")
    fld_sep.set(qn("w:fldCharType"), "separate")
    placeholder = OxmlElement("w:t")
    placeholder.text = "Right-click here and choose 'Update Field' to generate the table of contents."
    fld_sep.append(placeholder)
    fld_end = OxmlElement("w:fldChar")
    fld_end.set(qn("w:fldCharType"), "end")
    r = run._r
    r.append(fld_begin)
    r.append(instr)
    r.append(fld_sep)
    r.append(fld_end)


def _add_page_number_field(paragraph: Paragraph) -> None:
    run = paragraph.add_run()
    fld_begin = OxmlElement("w:fldChar")
    fld_begin.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText")
    instr.set(qn("xml:space"), "preserve")
    instr.text = "PAGE"
    fld_end = OxmlElement("w:fldChar")
    fld_end.set(qn("w:fldCharType"), "end")
    r = run._r
    r.append(fld_begin)
    r.append(instr)
    r.append(fld_end)


def _shade_cell(cell: _Cell, hex_color: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:fill"), hex_color)
    tc_pr.append(shd)


def _setup_styles(doc: Document) -> None:
    normal = doc.styles["Normal"]
    normal.font.name = "Calibri"
    normal.font.size = Pt(11)

    h1 = doc.styles["Heading 1"]
    h1.font.name = "Calibri"
    h1.font.size = Pt(16)
    h1.font.color.rgb = ACCENT_COLOR
    h1.font.bold = True

    h2 = doc.styles["Heading 2"]
    h2.font.name = "Calibri"
    h2.font.size = Pt(13)
    h2.font.color.rgb = ACCENT_COLOR


def _add_header_footer(doc: Document, title: str) -> None:
    section = doc.sections[0]
    header_p = section.header.paragraphs[0]
    header_p.text = title
    header_p.runs[0].font.size = Pt(9)
    header_p.runs[0].font.color.rgb = RGBColor(0x80, 0x80, 0x80)

    footer_p = section.footer.paragraphs[0]
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_p.add_run("Page ").font.size = Pt(9)
    _add_page_number_field(footer_p)


def _add_cover_page(doc: Document, plan: Plan, request_id: str) -> None:
    for _ in range(4):
        doc.add_paragraph()

    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_p.add_run(plan.title)
    run.font.size = Pt(28)
    run.font.bold = True
    run.font.color.rgb = ACCENT_COLOR

    subtitle_p = doc.add_paragraph()
    subtitle_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle_p.add_run(plan.document_type.replace("_", " ").title())
    sub_run.font.size = Pt(14)
    sub_run.font.color.rgb = RGBColor(0x40, 0x40, 0x40)

    if plan.audience:
        aud_p = doc.add_paragraph()
        aud_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        aud_p.add_run(f"Prepared for: {plan.audience}").font.size = Pt(11)

    meta_p = doc.add_paragraph()
    meta_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta_p.add_run(
        f"Generated by Autonomous Document Agent  |  {datetime.now().strftime('%d %B %Y')}  |  Ref: {request_id[:8]}"
    )
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(0x80, 0x80, 0x80)
    doc.add_page_break()


def _add_assumptions_box(doc: Document, assumptions: List[str]) -> None:
    if not assumptions:
        return
    doc.add_heading("Assumptions Made by the Agent", level=1)
    doc.add_paragraph(
        "The request did not fully specify every detail below. To produce a complete, "
        "usable document without back-and-forth clarification, the agent made the "
        "following reasonable assumptions:"
    )
    for a in assumptions:
        doc.add_paragraph(a, style="List Bullet")


def _add_table(doc: Document, columns: List[str], rows: List[Dict[str, Any]]) -> None:
    table = doc.add_table(rows=1, cols=len(columns))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.style = "Table Grid"
    hdr_cells = table.rows[0].cells
    for i, col in enumerate(columns):
        hdr_cells[i].text = ""
        run = hdr_cells[i].paragraphs[0].add_run(col)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        _shade_cell(hdr_cells[i], ACCENT_COLOR_HEX)
    for row_data in rows:
        cells = table.add_row().cells
        for i, col in enumerate(columns):
            cells[i].text = str(row_data.get(col, ""))


def _add_section(doc: Document, section: SectionContent) -> None:
    doc.add_heading(section.title, level=1)
    if section.revised:
        note = doc.add_paragraph()
        run = note.add_run("(refined by the agent's self-check pass)")
        run.font.italic = True
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x90, 0x90, 0x90)

    if section.table_columns:
        rows = section.content if isinstance(section.content, list) else []
        _add_table(doc, section.table_columns, rows)
    else:
        text = section.content if isinstance(section.content, str) else str(section.content)
        for para in [p for p in text.split("\n") if p.strip()]:
            doc.add_paragraph(para.strip())


def build_docx(plan: Plan, sections: List[SectionContent], request_id: str) -> Path:
    doc = Document()
    _setup_styles(doc)
    _add_header_footer(doc, plan.title)
    _add_cover_page(doc, plan, request_id)

    doc.add_heading("Contents", level=1)
    _add_toc_field(doc)
    doc.add_page_break()

    _add_assumptions_box(doc, plan.assumptions)
    for section in sections:
        _add_section(doc, section)

    out_path = config.OUTPUT_DIR / f"{request_id}.docx"
    doc.save(out_path)
    return out_path
